apiVersion: v1
kind: Service
metadata:
  labels:
    app: deeptalk-app
  name: deeptalk-app
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30080
  type: NodePort
  selector:
    app: deeptalk-app