version: '3.7'
services:
  app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - "8080:80"
    env_file:
      - app.env
    depends_on:
      - influxdb
      - grafana
  influxdb:
    image: influxdb
    environment:
      - INFLUXDB_DB=deeptalk
    ports:
      - "8086:8086"
    command:
      - '-config'
      - '/etc/influxdb/influxdb.conf'
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
