apiVersion: v1
kind: Service
metadata:
  labels:
    app: grafana
  name: {{ .Release.Name }}-grafana
spec:
  ports:
  - port: {{ .Values.grafana.service.port }}
    protocol: TCP
    targetPort: 3000
  type: {{ .Values.grafana.service.type }}
  selector:
    app: grafana