apiVersion: v1

kind: Service

metadata:
  name: demo-svc

spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: kubia
  # Service über alle Nodes erreichbar - mittels dem
  type: NodePort